"""initial schema

Revision ID: 92424f891b21
Revises: 
Create Date: 2025-11-27 01:15:29.044676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92424f891b21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('mother_full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('national_id', sa.String(length=60), nullable=True),
    sa.Column('preferred_time', sa.String(length=60), nullable=True),
    sa.Column('visit_reason', sa.String(length=180), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_confirmation_code'), 'appointments', ['confirmation_code'], unique=True)
    op.create_index(op.f('ix_appointments_visit_date'), 'appointments', ['visit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_visit_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_confirmation_code'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
